### ISSUE TITLE
why update alpha using log alpha?

### ISSUE THREAD

**Issue by SupernovaTitanium** [XinJingHao/SAC-Discrete-Pytorch#1]
Hi, I looked into your code and found out that you are replacing alpha with log alpha when calculating alpha loss. 
I also noticed that Chris did it too. what's the purpose of doing so? This does not match the definition of alpha loss in the paper.
I'm confused.

**Comment by XinJingHao** [comment]
To make sure that the Alpha>=0

----- 原始邮件 -----
发件人: "SupernovaTitanium" ***@***.***>
收件人: "XinJingHao/SAC-Discrete-Pytorch" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期二, 2023年 4 月 18日 下午 7:43:06
主题: [XinJingHao/SAC-Discrete-Pytorch] why update alpha using log alpha? (Issue #1)

Hi, I looked into your code and found out that you are replacing alpha with log alpha when calculating alpha loss. 
I also noticed that Chris did it too. what's the purpose of doing so? This does not match the definition of alpha loss in the paper.
I'm confused.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/XinJingHao/SAC-Discrete-Pytorch/issues/1
You are receiving this because you are subscribed to this thread.

Message ID: ***@***.***>
-- 
祝好！

-------------------------
上海交通大学电子信息与电气工程学院
辛靖豪

**Comment by SupernovaTitanium** [comment]
Thanks. I understand now.
